version: "3.1"

networks: 
    vk_bot:
        driver: bridge

services: 
    db:
        container_name: vk_bot
        image: sameersbn/postgresql:10-2
        environment: 
            PG_PASSWORD: $PGPASSWORD
        restart: always
        ports: 
            - 5432:5432
        networks: 
            - vk_bot
        volumes: 
            - ./postgres:/var/lib/postgresql
    
    tgbot:
        container_name: bot
        build:
            context: .
        command: python models.py
        command: python vk_bot.py
        restart: always
        networks: 
            - vk_bot
        env_file:
            - ".env"
        volumes: 
            - .:/src
        depends_on: 
            - db